### PR TITLE
Version 2, Pest 3

### PR DESCRIPTION
**Pull request by markhuot**

### CODE REVIEW

**Comment by bencroker** [comment]
Rooting for some progress on this since Craft 4.5.0 loosened its composer requirements 🚀

**Comment by markhuot** [comment]
Passing tests! Need to get docs generating and then this'll be ready to merge.

FYI, this will break `markhuot/craft-pest` in to two repos:

- `markhuot/craft-pest` which will eventually contain a Craft UI in the CP
- `markhuot/craft-pest-core` which contains the Pest hooks

Moving forward you should be able to `require --dev markhuot/craft-pest-core` if you want the Pest integration without the Plugin side of things. The `-core` repo is implemented as a Yii2 extension.

**Comment by bencroker** [comment]
Amazing work!! I’d be happy to contribute to docs if that would be helpful.

**Comment by aaronbushnell** [comment]
Hey @markhuot — is this version safe to use if I'm upgrading a Craft 3 site to Craft 4.5+? Wanted to pull this in but wasn't sure how close to release you were!

**Comment by markhuot** [comment]
Yup, should work on Craft 4.5+ now. You can either target `markhuot/craft-pest dev-v2` or if you don't want to enable the plugin just `composer require --dev markhuot/craft-pest-core` and that should work via a yii2 extension on your local install only.

**Pull request merged**
