### PR TITLE
Craft 4 support

### PR DESCRIPTION
**Pull request by ostark**
WIP
So far only mechanical work following phpstan.

* ~~`pest/Coverage.php` is still broken because of the different signature of `Twig\Environment::loadTemplate()` - not sure what to do~~ 
* some factories have broken types 

* [x] Add `$this->actingAs($user)` to support CP requests
* [ ] Add `$this->post()` request support
* [ ] Add `$this->json($verb, $url, $data)` requests support
* [ ] Add `$response->seeJsonEquals()` / `$response->seeJson()` assertion
* [ ] Refactor HTTP service

### CODE REVIEW

**Comment by ostark** [comment]
Please let me know if this PR is useful to you and how to continue.

**Comment by ostark** [comment]
Unfortunately, I struggle to get the docker setup up and running.

**Comment by markhuot** [comment]
Thank you! This is amazing! I'm working on a project that is using this in Craft 3 right now so I'm not ready to dive head first in to Craft 4, but certainly welcome the PR.

Types FTW and as long as I can merge this and keep Craft 3 support I don't have any concerns. Let me test this out later this week and get back to you.

**Comment by ostark** [comment]
for some reason rendering the body does not work (tested against the bike demo site)

dd(get('/'))

```
craft\web\Response^ {#948
  -_events: []
  -_eventWildcards: []
  -_behaviors: array:2 [
    "testableResponse" => markhuot\craftpest\behaviors\TestableResponseBehavior^ {#1222
      +owner: craft\web\Response^ {#948}
      -_attachedEvents: []
    }
    "template" => craft\web\TemplateResponseBehavior^ {#1238
      +owner: craft\web\Response^ {#948}
      -_attachedEvents: []
      +template: "_views/homepage/index"
      +variables: array:2 [
        "entry" => craft\elements\Entry^ {#1216
          -_events: []
          -_eventWildcards: []
          -_behaviors: array:2 [
            "customFields" => craft\behaviors\CustomFieldBehavior^ {#1243
              +owner: craft\elements\Entry^ {#1216}
              -_attachedEvents: []
              +hasMethods: false
              +canSetProperties: false
              +color: null
              +bikeType: null
              +colors: null
              +material: null
              +body: null
              +heading: "Made for fun since 1986"
              +subheading: null
              +stars: null
              +product: null
              +contentBlocks: null
              +intro: null
              +products: null
              +image: null
              +form: null
              +showForm: null
              +equipmentType: null
              +productImages: null
              +mainImage: null
              +planFeatures: null
              +plainText1: null
              +plainText2: null
              +icon: null
              +footerNav: null
              +productCategories: null
              +pages: null
              +geometry: null
              +button: null
              +ariaLabel: null
              +buttonUrl: null
              +label: null
              +categoryLink: null
              +entryLink: null
              +seo: "{"bundleVersion":"1.0.22","sourceBundleType":"field","sourceId":null,"sourceName":null,"sourceHandle":null,"sourceType":"field","typeId":null,"sourceTemplate":"","sourceSiteId":null,"sourceAltSiteSettings":[],"sourceDateUpdated":"2021-04-12T04:06:06-07:00","metaGlobalVars":{"language":null,"mainEntityOfPage":"","seoTitle":"Huge range of bicycles for all disciplines!","siteNamePosition":"","seoDescription":"Spoke & Chain is a large online bike store that caters for all of your cycling needs.","seoKeywords":"","seoImage":"","seoImageWidth":"","seoImageHeight":"","seoImageDescription":"","canonicalUrl":"","robots":"","ogType":"","ogTitle":"","ogSiteNamePosition":"","ogDescription":"","ogImage":"","ogImageWidth":"","ogImageHeight":"","ogImageDescription":"","twitterCard":"","twitterCreator":"","twitterTitle":"","twitterSiteNamePosition":"","twitterDescription":"","twitterImage":"","twitterImageWidth":"","twitterImageHeight":"","twitterImageDescription":""},"metaSiteVars":{"siteName":"Spoke and Chain","identity":null,"creator":null,"twitterHandle":"","facebookProfileId":"","facebookAppId":"","googleSiteVerification":"","bingSiteVerification":"","pinterestSiteVerification":"","sameAsLinks":[],"siteLinksSearchTarget":"","siteLinksQueryInput":"","referrer":"no-referrer-when-downgrade","additionalSitemapUrls":[],"additionalSitemapUrlsDateUpdated":null,"additionalSitemaps":[]},"metaSitemapVars":{"sitemapUrls":true,"sitemapAssets":true,"sitemapFiles":true,"sitemapAltLinks":true,"sitemapChangeFreq":"weekly","sitemapPriority":0.5,"sitemapLimit":null,"structureDepth":null,"sitemapImageFieldMap":[],"sitemapVideoFieldMap":[]},"metaContainers":{"MetaTagContainergeneral":{"data":[],"name":"General","description":"General Meta Tags","class":"nystudio107\\seomatic\\models\\MetaTagContainer","handle":"general","include":true,"dependencies":[],"clearCache":false},"MetaTagContaineropengraph":{"data":[],"name":"Facebook","description":"Facebook OpenGraph Meta Tags","class":"nystudio107\\seomatic\\models\\MetaTagContainer","handle":"opengraph","include":true,"dependencies":[],"clearCache":false},"MetaTagContainertwitter":{"data":[],"name":"Twitter","description":"Twitter Card Meta Tags","class":"nystudio107\\seomatic\\models\\MetaTagContainer","handle":"twitter","include":true,"dependencies":[],"clearCache":false},"MetaTagContainermiscellaneous":{"data":[],"name":"Miscellaneous","description":"Miscellaneous Meta Tags","class":"nystudio107\\seomatic\\models\\MetaTagContainer","handle":"miscellaneous","include":true,"dependencies":[],"clearCache":false},"MetaLinkContainergeneral":{"data":[],"name":"General","description":"Link Tags","class":"nystudio107\\seomatic\\models\\MetaLinkContainer","handle":"general","include":true,"dependencies":[],"clearCache":false},"MetaScriptContainergeneral":{"data":[],"position":1,"name":"General","description":"Script Tags","class":"nystudio107\\seomatic\\models\\MetaScriptContainer","handle":"general","include":true,"dependencies":[],"clearCache":false},"MetaJsonLdContainergeneral":{"data":[],"name":"General","description":"JsonLd Tags","class":"nystudio107\\seomatic\\models\\MetaJsonLdContainer","handle":"general","include":true,"dependencies":[],"clearCache":false},"MetaTitleContainergeneral":{"data":[],"name":"General","description":"Meta Title Tag","class":"nystudio107\\seomatic\\models\\MetaTitleContainer","handle":"general","include":true,"dependencies":[],"clearCache":false}},"redirectsContainer":[],"frontendTemplatesContainer":{"data":[],"name":null,"description":null,"class":"nystudio107\\seomatic\\models\\FrontendTemplateContainer","handle":null,"include":true,"dependencies":null,"clearCache":false},"metaBundleSettings":{"siteType":"","siteSubType":"","siteSpecificType":"","seoTitleSource":"fromCustom","seoTitleField":"title","siteNamePositionSource":"sameAsGlobal","seoDescriptionSource":"fromCustom","seoDescriptionField":"title","seoKeywordsSource":"fromCustom","seoKeywordsField":"","seoImageIds":"","seoImageSource":"fromAsset","seoImageField":"mainImage","seoImageTransform":"1","seoImageTransformMode":"crop","seoImageDescriptionSource":"fromCustom","seoImageDescriptionField":"","twitterCreatorSource":"sameAsSite","twitterCreatorField":"","twitterTitleSource":"sameAsSeo","twitterTitleField":"","twitterSiteNamePositionSource":"sameAsGlobal","twitterDescriptionSource":"sameAsSeo","twitterDescriptionField":"","twitterImageIds":[],"twitterImageSource":"sameAsSeo","twitterImageField":"","twitterImageTransform":true,"twitterImageTransformMode":"crop","twitterImageDescriptionSource":"sameAsSeo","twitterImageDescriptionField":"","ogTitleSource":"sameAsSeo","ogTitleField":"","ogSiteNamePositionSource":"sameAsGlobal","ogDescriptionSource":"sameAsSeo","ogDescriptionField":"","ogImageIds":[],"ogImageSource":"sameAsSeo","ogImageField":"","ogImageTransform":true,"ogImageTransformMode":"crop","ogImageDescriptionSource":"sameAsSeo","ogImageDescriptionField":""}}"
              +businessHours: null
              +businessAddress: null
              +imageAlt: null
              +imageCaption: null
              -_customFieldValues: []
            }
            0 => markhuot\craftpest\behaviors\Macroable^ {#1242
              +owner: craft\elements\Entry^ {#1216}
              -_attachedEvents: []
            }
          ]
          -_errors: null
          -_validators: null
          -_scenario: "default"
          #revisionCreatorId: null
          #revisionNotes: null
          -_canonicalId: null
          -_canonical: null
          -_canonicalAnySite: null
          -_canonicalUid: null
          -_outdatedAttributes: null
          -_modifiedAttributes: null
          -_outdatedFields: null
          -_modifiedFields: null
          -_initialized: true
          -_fieldsByHandle: []
          -_fieldParamNamePrefix: null
          -_normalizedFieldValues: null
          -_allDirty: false
          -_dirtyAttributes: []
          -_savedTitle: "Homepage"
          -_dirtyFields: []
          -_nextElement: false
          -_prevElement: false
          -_parentId: null
          -_parent: null
          -_hasNewParent: null
          -_prevSibling: null
          -_nextSibling: null
          -_eagerLoadedElements: []
          -_eagerLoadedElementCounts: []
          -_currentRevision: null
          -_enabledForSite: true
          -_uiLabel: null
          -_isFresh: null
          +id: 20
          +tempId: null
          +draftId: null
          +revisionId: null
          +isProvisionalDraft: false
          +uid: "07553ba4-3c16-4164-a7fc-146c0b2acc50"
          +siteSettingsId: 20
          +fieldLayoutId: null
          +structureId: null
          +contentId: 19
          +enabled: true
          +archived: false
          +siteId: 1
          +title: "Homepage"
          +slug: "homepage"
          +uri: "__home__"
          +dateCreated: DateTime @1601563723 {#1219
            date: 2020-10-01 07:48:43.0 America/Los_Angeles (-07:00)
          }
          +dateUpdated: DateTime @1646913878 {#1218
            date: 2022-03-10 04:04:38.0 America/Los_Angeles (-08:00)
          }
          +dateLastMerged: null
          +dateDeleted: null
          +root: null
          +lft: null
          +rgt: null
          +level: null
          +searchScore: null
          +trashed: false
          +awaitingFieldValues: false
          +propagating: false
          +propagateAll: false
          +newSiteIds: []
          +isNewForSite: false
          +resaving: false
          +duplicateOf: null
          +firstSave: false
          +mergingCanonicalChanges: false
          +updatingFromDerivative: false
          +previewing: false
          +hardDelete: false
          +sectionId: 2
          +postDate: DateTime @1601563680 {#1217
            date: 2020-10-01 07:48:00.0 America/Los_Angeles (-07:00)
          }
          +expiryDate: null
          +deletedWithEntryType: false
          +_authorId: null
          -_author: null
          -_typeId: 3
          -_oldTypeId: 3
        }
        "variables" => array:1 [
          "entry" => craft\elements\Entry^ {#1216}
        ]
      ]
      +templateMode: null
    }
  ]
  +exitStatus: 0
  +format: "template"
  +acceptMimeType: null
  +acceptParams: []
  +formatters: array:6 [
    "html" => array:1 [
      "class" => "yii\web\HtmlResponseFormatter"
    ]
    "xml" => array:1 [
      "class" => "yii\web\XmlResponseFormatter"
    ]
    "json" => array:1 [
      "class" => "yii\web\JsonResponseFormatter"
    ]
    "jsonp" => array:2 [
      "class" => "yii\web\JsonResponseFormatter"
      "useJsonp" => true
    ]
    "csv" => array:1 [
      "class" => "craft\web\CsvResponseFormatter"
    ]
    "template" => "craft\web\TemplateResponseFormatter"
  ]
  +data: null
  +content: null
  +stream: null
  +charset: "UTF-8"
  +statusText: "OK"
  +version: "1.1"
  +isSent: false
  -_statusCode: 200
  -_headers: null
  -_cookies: null
  -_isPrepared: false
}
```

any idea?

**Comment by ostark** [comment]
response->content is null

must be somehow related to https://github.com/craftcms/cms/blob/develop/src/web/TemplateResponseFormatter.php

**Comment by ostark** [comment]
The Yii Request/Response model sucks. I managed somehow to get a response body.
Assertions are still broken ... I'll try tomorrow to fix them.

**Comment by ostark** [comment]
Slow progress: Basic HTTP GET works.

I didn't manage to support `test()->throws(Exception::class)`

Tons of other things are missing and need tests.

**Comment by ostark** [comment]
Please let me know if you think I'm changing too many things.

**Pull request merged**
