### PR TITLE
WIP Forms

### PR DESCRIPTION
**Pull request by markhuot**
I have a WIP for form POSTs via this PR. It makes the following test work,

```php
it ('test', function () {
    $this->get('/form')
        ->fill('firstFormTextField', 'test')
        ->submit()
        ->querySelector('#form-data')
        ->expect()
        ->innerHTML->toBe(json_encode(['firstFormTextField' => 'test']));
});
```

I had to muck around a bit with the request builder to get the right body params working. It works with JSON, I need to get it working with form data still. /cc @ostark

### CODE REVIEW

**Comment by ostark** [comment]
The interface feels odd to me

->submit() // returns response
->querySelector('#form-data') // id=form-data
->expect() // ???
->innerHTML // ??
->toBe(json_encode()) // json??

**Comment by markhuot** [comment]
Oh, that bit you highlighted is just me validating the response. The form template prints any posted data after submitting to itself. So, after the submission I'm just validating that the data actually did make it in to `$_POST` data.

**Comment by ostark** [comment]
Everything until submit() is okay, but the steps after are confusing to me

>querySelector('#form-data') 
->expect() 
->innerHTML 
->toBe(json_encode())

**Comment by markhuot** [comment]
Ah, yea, in `form.twig` I have the following,

```twig

<html>
<body>
<div id="first-form">
    <form action="/form" method="post">
        <input name="firstFormTextField">
        <input type="submit">
    </form>
</div>

<pre id="form-data">{{ craft.app.request.getBodyParams()|json_encode }}</pre>
</body>
</html>
```

So, this test gets the page, fills in `firstFormTextField` and submits it to itself. From there the resulting page will have that `<pre/>` element filled out with JSON encoded representation of the posted data. It’s a way for me to check that the resulting POST request actually contained the data I expected it to contain.

I just pushed a fix that now has it working with `application/json` and `multipart/form-data` so it’s a lot more resilient. Should work for all forms except for file uploads, is my guess. Going to bang on it some more with some projects that I’ve been putting off writing form tests for.

**Comment by ostark** [comment]
Please have a look at https://github.com/markhuot/craft-pest/pull/22/files#diff-59e93e6fb927abb49192fbc83b7ef73371ad3e093b25b8177a5aea0772949f65

It makes use of `DomCrawler\Form` which provides a lot of forms features "for free" with specific methods for special fields (select, checkbox, ...) I think it's better than maintaining our own $formData collection. 



How to continue with both branches?

**Pull request closed without merging**
